[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"

[[services]]
name = "web"
protocol = "tcp"
internal_port = 3000
auto_start = true
healthcheck_path = "/health"
healthcheck_timeout = 180
healthcheck_interval = 30

[services.ports]
port = 3000
internal_port = 3000 