[build]
builder = "nixpacks"
buildCommand = "npm run build:all"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"
PORT = "3000"

[[services]]
name = "web"
protocol = "tcp"
internal_port = 3000
auto_start = true

[services.ports]
port = 3000
internal_port = 3000 